name: compreaidelivery
description: Delivery de supermecados para a cidade de Catalao-Go

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"



dependencies:
  flutter:
    sdk: flutter

  mask_text_input_formatter: ^1.0.7
  cpf_cnpj_validator: ^1.0.5
  keyboard_actions: ^3.3.0+1
  brasil_fields: ^0.2.0


  http:
  credit_card_type_detector: ^1.1.0
  google_map_polyline:
  maps_toolkit: ^1.0.1+3
  flip_card: ^0.4.4
  flushbar: ^1.10.4
  google_maps_utils:
  mysql1: ^0.17.1
  google_sign_in:
  geolocator: ^5.3.1
  cloud_functions: 
  google_sign_in_platform_interface: ^1.1.1
  google_maps_flutter: ^0.5.29+1
  location: ^2.3.5
  apple_sign_in: ^0.1.0
  sign_in_with_apple: ^2.5.2
  slide_popup_dialog: ^0.0.2
  qr_flutter: ^3.1.0
  flutter_staggered_grid_view: ^0.3.0
  carousel_pro: ^1.0.0
  flutter_icons: ^1.1.0
  carousel_slider: ^2.0.0
  flutter_login:
  firebase_messaging: 
  sqljocky5: ^2.2.1
  date_format:
  flutter_credit_card: 0.1.0
  pdf: ^1.8.1
  flare_flutter: ^2.0.3
  cloud_firestore: 
  transparent_image: ^1.0.0
  scoped_model: ^1.0.1
  firebase_auth: ^0.15.3
  floating_search_bar:
  firebase_core:
  grouped_buttons:
  rxdart: ^0.20.0
  font_awesome_flutter: ^8.0.1
  flutter_html: ^1.0.0-pre.1
  search_widget:
  flutter_local_notifications:
  geocoder:
  flutter_auth_buttons:
  nice_button:
  image_picker: ^0.6.0+17
  firebase_storage:
  device_info:
  bloc_pattern: ^1.5.2
  fluttertoast: ^6.0.1
  image_cropper: ^1.2.1
  shared_preferences: ^0.5.7
  path_provider: ^1.6.7
  url_launcher: ^5.1.1
  dio: ^3.0.9
  geocoding: ^1.0.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dependency_overrides:

  
dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_launcher_icons:
  lint: ^1.2.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:

    - family: QuickSand
      fonts:
        - asset: fonts/quicksand-bold.ttf

    - family: Roboto-Light
      fonts:
        - asset: fonts/Roboto-Bold.ttf

    - family: RobotoBold
      fonts:
        - asset: fonts/Roboto-Bold.ttf


